Kintex-7: include/xbasic_types.h File Reference
xbasic_types.h File Reference
Classes
struct Xuint64
Defines
#define XBASIC_TYPES_H
#define TRUE 1
#define FALSE 0
#define NULL 0
#define XNULL NULL
#define XTRUE TRUE
#define XFALSE FALSE
#define XCOMPONENT_IS_READY 0x11111111
#define XCOMPONENT_IS_STARTED 0x22222222
#define XIL_COMPONENT_IS_READY XCOMPONENT_IS_READY
#define XIL_COMPONENT_IS_STARTED XCOMPONENT_IS_STARTED
#define XTEST_PASSED 0
#define XTEST_FAILED 1
#define XASSERT_NONE 0
#define XASSERT_OCCURRED 1
#define XUINT64_MSW(x) ((x).Upper)
#define XUINT64_LSW(x) ((x).Lower)
#define XASSERT_VOID(expression)
#define XASSERT_NONVOID(expression)
#define XASSERT_VOID_ALWAYS()
#define XASSERT_NONVOID_ALWAYS()
#define Xil_AssertVoid XASSERT_VOID
#define Xil_AssertNonvoid XASSERT_NONVOID
#define Xil_AssertVoidAlways XASSERT_VOID_ALWAYS
#define Xil_AssertNonVoidAlways XASSERT_NONVOID_ALWAYS
Typedefs
typedef void(* XInterruptHandler)(void *InstancePtr)
typedef void(* XExceptionHandler)(void *InstancePtr)
typedef void(* XAssertCallback)(char *FilenamePtr, int LineNumber)
Legacy types
Deprecated legacy types.
typedef unsigned char Xuint8
typedef char Xint8
typedef unsigned short Xuint16
typedef short Xint16
typedef unsigned long Xuint32
typedef long Xint32
typedef float Xfloat32
typedef double Xfloat64
typedef unsigned long Xboolean
New types
New simple types.
typedef Xuint32 u32
typedef Xuint16 u16
typedef Xuint8 u8
Functions
void XAssert (char *, int)
void XAssertSetCallback (XAssertCallback Routine)
void XNullHandler (void *NullParameter)
Variables
unsigned int XAssertStatus
Detailed Description
This file contains basic types for Xilinx software IP. These types do not follow the standard naming convention with respect to using the component name in front of each name because they are considered to be primitives.
Note:
This file contains items which are architecture dependent.
MODIFICATION HISTORY:
Ver Date Changes ---- -------- ------------------------------------------------------- 1.0 5/15/12 First release
Define Documentation
#define XASSERT_NONVOID (expression)
Value:
{                                                  \
    if (expression)                                \
    {                                              \
        XAssertStatus = XASSERT_NONE;              \
    }                                              \
    else                                           \
    {                                              \
        XAssert(__FILE__, __LINE__);               \
                XAssertStatus = XASSERT_OCCURRED;  \
        return 0;                                  \
    }                                              \
}
This assert macro is to be used for functions that do return a value. This in conjunction with the XWaitInAssert boolean can be used to accomodate tests so that asserts which fail allow execution to continue.
Parameters:
expression is the expression to evaluate. If it evaluates to false, the assert occurs.
Returns:
Returns 0 unless the XWaitInAssert variable is true, in which case no return is made and an infinite loop is entered.
Note:
None.
#define XASSERT_NONVOID_ALWAYS ()
Value:
{                                                  \
   XAssert(__FILE__, __LINE__);                    \
           XAssertStatus = XASSERT_OCCURRED;       \
   return 0;                                       \
}
Always assert. This assert macro is to be used for functions that do return a value. Use for instances where an assert should always occur.
Returns:
Returns void unless the XWaitInAssert variable is true, in which case no return is made and an infinite loop is entered.
Note:
None.
#define XASSERT_VOID (expression)
Value:
{                                                  \
    if (expression)                                \
    {                                              \
        XAssertStatus = XASSERT_NONE;              \
    }                                              \
    else                                           \
    {                                              \
        XAssert(__FILE__, __LINE__);               \
                XAssertStatus = XASSERT_OCCURRED;  \
        return;                                    \
    }                                              \
}
This assert macro is to be used for functions that do not return anything (void). This in conjunction with the XWaitInAssert boolean can be used to accomodate tests so that asserts which fail allow execution to continue.
Parameters:
expression is the expression to evaluate. If it evaluates to false, the assert occurs.
Returns:
Returns void unless the XWaitInAssert variable is true, in which case no return is made and an infinite loop is entered.
Note:
None.
#define XASSERT_VOID_ALWAYS ()
Value:
{                                                  \
   XAssert(__FILE__, __LINE__);                    \
           XAssertStatus = XASSERT_OCCURRED;       \
   return;                                         \
}
Always assert. This assert macro is to be used for functions that do not return anything (void). Use for instances where an assert should always occur.
Returns:
Returns void unless the XWaitInAssert variable is true, in which case no return is made and an infinite loop is entered.
Note:
None.
#define XCOMPONENT_IS_READY 0x11111111
Component has been initialized
#define XCOMPONENT_IS_STARTED 0x22222222
Component has been started
#define XFALSE FALSE
Legacy return type. Deprecated.
#define XNULL NULL
Legacy return type. Deprecated.
#define XTRUE TRUE
Legacy return type. Deprecated.
#define XUINT64_LSW (x) ((x).Lower)
Return the least significant half of the 64 bit data type.
Parameters:
x is the 64 bit word.
Returns:
The lower 32 bits of the 64 bit word.
Note:
None.
#define XUINT64_MSW (x) ((x).Upper)
Return the most significant half of the 64 bit data type.
Parameters:
x is the 64 bit word.
Returns:
The upper 32 bits of the 64 bit word.
Note:
None.
Typedef Documentation
typedef void(* XAssertCallback)(char *FilenamePtr, int LineNumber)
This data type defines a callback to be invoked when an assert occurs. The callback is invoked only when asserts are enabled
typedef unsigned long Xboolean
boolean (XTRUE or XFALSE)
typedef void(* XExceptionHandler)(void *InstancePtr)
This data type defines an exception handler for a processor. The argument points to the instance of the component
typedef float Xfloat32
32-bit floating point
typedef double Xfloat64
64-bit double precision FP
typedef short Xint16
signed 16-bit
typedef long Xint32
signed 32-bit
typedef char Xint8
signed 8-bit
typedef void(* XInterruptHandler)(void *InstancePtr)
This data type defines an interrupt handler for a device. The argument points to the instance of the component
typedef unsigned short Xuint16
unsigned 16-bit
typedef unsigned long Xuint32
unsigned 32-bit
typedef unsigned char Xuint8
unsigned 8-bit
Function Documentation
void XAssert (char * File, int Line)
Implements assert. Currently, it calls a user-defined callback function if one has been set. Then, it potentially enters an infinite loop depending on the value of the XWaitInAssert variable.
Parameters:
File is the name of the filename of the source
Line is the linenumber within File
Returns:
None.
Note:
None.
References XAssert().
Referenced by XAssert().
void XAssertSetCallback (XAssertCallback Routine)
Sets up a callback function to be invoked when an assert occurs. If there was already a callback installed, then it is replaced.
Parameters:
Routine is the callback to be invoked when an assert is taken
Returns:
None.
Note:
This function has no effect if NDEBUG is set
References XAssertSetCallback().
Referenced by XAssertSetCallback().
void XNullHandler (void * NullParameter)
Null handler function. This follows the XInterruptHandler signature for interrupt handlers. It can be used to assign a null handler (a stub) to an interrupt controller vector table.
Parameters:
NullParameter is an arbitrary void pointer and not used.
Returns:
None.
Note:
None.
References XNullHandler().
Referenced by XNullHandler().
Variable Documentation
unsigned int XAssertStatus
This variable allows testing to be done easier with asserts. An assert sets this variable such that a driver can evaluate this variable to determine if an assert occurred.