Kintex-7: include/xdma_user.h File Reference
xdma_user.h File Reference
#include <xpmon_be.h>
#include <linux/ethtool.h>
#include <linux/delay.h>
Classes
struct PktBuf
struct UserState
struct UserPtrs
Defines
#define XDMA_USER_H
#define STATUS_REG_OFFSET 0x9008
#define PERFORMANCE_MODE 0
#define ETHERNET_APPMODE 1
#define RAWETHERNET_MODE 2
Driver and engine states.
#define UNINITIALIZED 0
#define INITIALIZED 1
#define USER_ASSIGNED 2
#define UNREGISTERING 3
Packet information set/read by the user drivers.
These flags match with the status reported by DMA. Additional flags should be assigned from available bits.
#define PKT_SOP 0x80000000
#define PKT_EOP 0x40000000
#define PKT_ERROR 0x10000000
#define PKT_UNUSED 0x00004000
#define PKT_ALL 0x00800000
Functions
Initialization and control functions in xdma.c
void * DmaRegister (int engine, int bar, UserPtrs *uptr, int pktsize)
int DmaUnregister (void *handle)
void * DmaBaseAddress (int bar)
int DmaMac_WriteReg (int offset, int data)
int DmaMac_ReadReg (int offset)
int DmaSendPages_Tx (void *handle, PktBuf **pkts, int numpkts)
int DmaSendPages (void *handle, PktBuf **pkts, int numpkts)
int DmaSendPkt (void *handle, PktBuf *pkts, int numpkts)
void Dma_get_ringparam (void *handle, struct ethtool_ringparam *ering)
Detailed Description
This file contains the data required for the interface between the base DMA driver (xdma) and the application-specific drivers, for example,
This interface has been architected in order to make it possible to easily substitute the application-specific drivers that come with this TRD with other application-specific drivers, without re-writing the common DMA-handling functionality.
Some xdma functions are called directly by the application-specific driver and some are callbacks registered by the application-specific driver, and are called by xdma.
 Application-Specific Driver                               xdma Driver
                               Driver Registration
                 ---------------------------------------------->
                             Driver De-registration
                 ---------------------------------------------->
                           Transmit Block/Packet Data
                 ---------------------------------------------->
                            Complete Initialization
                <----------------------------------------------
                            Complete Driver Removal
                <----------------------------------------------
                            Complete Interrupt Tasks
                <----------------------------------------------
                             Get Packet Buffer for RX
                <----------------------------------------------
                               Return Packet Buffer
                <----------------------------------------------
                                    Set State
                <----------------------------------------------
                                    Get State
                <----------------------------------------------
Driver Registration/De-registration
The application-specific drivers are dependent on the DMA driver and can be inserted as Linux kernel modules only after xdma has been loaded.
To register itself with xdma, the application-specific driver does the following, while specifying the engine number and BAR number it requires, a set of function callback pointers, and the minimum packet size it normally uses -
 Handle = DmaRegister(int Engine, int Bar, UserPtrs * uptr, int PktSize);
The application-specific driver requires to know the kernel logical address of the desired BAR in order to do any device-specific initializations that may be required. For example, the xgbeth driver requires to program the TEMAC and PHY registers, while the xaui driver requires to control the test configuration.
Before returning to the caller, DmaRegister() will invoke the function callback registered to complete the initialization process, while specifying the BAR's logical address, and a private data pointer that was passed to it during registration. privData can be used by the user driver to differentiate between multiple DmaRegister() invocations -
 (uptr->UserInit)(BARbase, privData);
Note: The application-specific driver's UserInit() function call must be written in such a way that it works fine even when the DmaRegister() call is not yet complete.
If the registration process is successful, a handle is returned which should be used in all other function calls to xdma.
To unregister itself from xdma, the application-specific driver does the following, while passing the handle it received after registration -
 DmaUnregister(Handle);
Before returning to the caller, DmaUnregister() will invoke the function callback registered to enable any device-specific programming to be done as part of the de-registration process.
 (uptr->UserRemove)(Handle, privData);
Before returning to the caller, DmaUnregister() also returns all the packet buffers that had been passed to it for transmission or reception. Incase these buffers are still unused, they are flagged as PKT_UNUSED.
 (uptr->UserPutPkt)(Handle, PktBuf * pkts, int NumPkts, privData);
Note: UserRemove() is not being invoked in xdma v1.00, and will be added in the future.
Buffer Handling
For better performance, the DMA driver always sets up large buffer descriptor (BD) rings, one for transmission and one for reception. The TX BD ring will be consumed only when there is data for transmission. The RX BD ring, on the other hand, will be entirely submitted for DMA in order to maximize performance.
Data Transmission
When the application-specific driver wants to transmit a data block or packet, it invokes the following, while passing an array of one or more packets to be transmitted -
 DmaSendPkt(Handle, PktBuf * pkts, int NumPkts);
When data transmission is completed, the packet buffers will be returned to the application-specific driver by invoking the following -
 (uptr->UserPutPkt)(Handle, PktBuf * pkts, int NumPkts, privData);
It is important to return these buffers to the application-specific driver even though they are TX packets, since they would need to be freed or re-used as the case may be.
Data Reception
The DMA driver needs to set up the complete BD ring with buffers ready for reception. Hence, it invokes the following, while specifying the number of packet buffers it wants, and their size -
 (uptr->UserGetPkt)(Handle, PktBuf * pkts, uint Size, int NumPkts, privData);
As data reception happens and buffers get used, they are returned to the application-specific driver, by invoking the following -
 (uptr->UserPutPkt)(Handle, PktBuf * pkts, int NumPkts, privData);
The DMA driver will again invoke UserGetPkt() in order to replenish the used BDs in its BD ring.
Interrupts
The DMA driver can operate in either a polled mode or interrupt-driven mode, by modifying a compile-time flag. The application-specific driver can optionally enable application-specific interrupts. When an interrupt occurs, the DMA driver will invoke the following, to enable handling of these interrupt events -
 (uptr->UserIntr)(Handle, privData);
Note: This callback is not being invoked by xdma v1.00, and will be added in the future.
Configuration, Status and Statistics
The Xilinx Performance Monitor GUI (xpmon) can be used to initiate a data transfer test and measure DMA payload and PCIe link performance. xdma invokes the following, while specifying whether loopback is enabled or not, and the minimum/maximum bounds of packet sizes -
 (uptr->UserSetState)(Handle, UserState * ustate, privData);
The same callback is used to start a test, and to stop a test.
xdma invokes the following, in order to get current state of the application-specific driver -
 (uptr->UserGetState)(Handle, UserState * ustate, privData);
Information regarding current test state, link state, total number of buffers is returned and can be displayed in the xpmon GUI.
MODIFICATION HISTORY:
Ver Date Changes ----- -------- ------------------------------------------------------- 1.0 5/15/12 First release
Define Documentation
#define INITIALIZED 1
After probe
Referenced by Dma_Initialize(), DmaBaseAddress(), DmaRegister(), and DmaUnregister().
#define PKT_ALL 0x00800000
All fragments must be sent
#define PKT_EOP 0x40000000
Buffer is the end-of-packet
#define PKT_ERROR 0x10000000
Error while processing buffer
#define PKT_SOP 0x80000000
Buffer is the start-of-packet
#define PKT_UNUSED 0x00004000
Buffer is being returned unused
Referenced by descriptor_free().
#define UNINITIALIZED 0
State at system start
#define UNREGISTERING 3
In the process of unregistering
Referenced by DmaUnregister().
#define USER_ASSIGNED 2
Engine assigned to user
Referenced by DmaRegister(), and DmaUnregister().
Function Documentation
void* DmaBaseAddress (int bar)
This function returns the DMA base address to the user driver
In 10G support, the MAC address registers are not mapped to MAC address space. The MAC address registers are mapped to the DMA address area. Hence, the user driver should know the DMA base address, so that it can access the MAC address registers to Set/Get MAC address.
Parameters:
bar is the BAR register the user driver wants to use.
Returns:
DMABaseAddress
References privData::baseVAddr, dmaData, and INITIALIZED.
void* DmaRegister (int engine, int bar, UserPtrs * uptr, int pktsize)
This function must be called by the user driver to register itself with the base DMA driver. After doing required checks to verify the choice of engine and BAR register, it initializes the engine and the BD ring associated with the engine, and enables interrupts if required.
Only one user is supported per engine at any given time. Incase the engine has already been registered with another user driver, an error will be returned.
Parameters:
engine is the DMA engine the user driver wants to use.
bar is the BAR register the user driver wants to use.
uptr is a pointer to the function callbacks in the user driver.
pktsize is the size of packets that the user driver will normally use.
Returns:
NULL incase of any error in completing the registration.
Handle with which the user driver is registered.
Note:
This function should not be called in an interrupt context
References privData::baseVAddr, Dma_Engine::BdRing, descriptor_init(), privData::Dma, Dma_BdRingStart(), Dma_mEngIntEnable, dmaData, privData::engineMask, Dma_Engine::EngineState, INITIALIZED, Dma_Engine::pdev, Dma_Engine::pktSize, UserPtrs::privData, Dma_Engine::user, USER_ASSIGNED, privData::userCount, UserPtrs::UserInit, and UserPtrs::versionReg.
int DmaUnregister (void * handle)
This function must be called by the user driver to unregister itself from the base DMA driver. After doing required checks to verify the handle and engine state, the DMA engine is reset, interrupts are disabled if required, and the BD ring is freed, while returning all the packet buffers to the user driver.
Parameters:
handle is the handle which was assigned during the registration process.
Returns:
XST_FAILURE incase of any error
0 incase of success
Note:
This function should not be called in an interrupt context
References descriptor_free(), Dma_Reset(), dmaData, Dma_Engine::EngineState, INITIALIZED, Dma_Engine::pdev, UNREGISTERING, USER_ASSIGNED, and privData::userCount.