Kintex-7: xdma/xdma_user.c File Reference
xdma_user.c File Reference
#include <linux/kernel.h>
#include <linux/timer.h>
#include <linux/jiffies.h>
#include <linux/pci.h>
#include <linux/mm.h>
#include <linux/spinlock.h>
#include <linux/pagemap.h>
#include "xbasic_types.h"
#include "xdebug.h"
#include "xstatus.h"
#include "xio.h"
#include "xdma.h"
#include "xdma_bd.h"
#include "xdma_user.h"
#include "xdma_hw.h"
Functions
void * DmaRegister (int engine, int bar, UserPtrs *uptr, int pktsize)
int DmaUnregister (void *handle)
void * DmaBaseAddress (int bar)
int DmaMac_WriteReg (int offset, int data)
int DmaMac_ReadReg (int offset)
int DmaSendPages_Tx (void *handle, PktBuf **pkts, int numpkts)
int DmaSendPages (void *handle, PktBuf **pkts, int numpkts)
int DmaSendPkt (void *handle, PktBuf *pkts, int numpkts)
void Dma_get_ringparam (void *handle, struct ethtool_ringparam *ering)
Detailed Description
Contains the APIs used by the application-specific drivers.
Author: Xilinx, Inc.
2007-2010 (c) Xilinx, Inc. This file is licensed uner the terms of the GNU General Public License version 2.1. This program is licensed "as is" without any warranty of any kind, whether express or implied.
MODIFICATION HISTORY:
Ver Date Changes ----- -------- ------------------------------------------------------- 1.0 05/15/12 First release
Function Documentation
void* DmaBaseAddress (int bar)
This function returns the DMA base address to the user driver
In 10G support, the MAC address registers are not mapped to MAC address space. The MAC address registers are mapped to the DMA address area. Hence, the user driver should know the DMA base address, so that it can access the MAC address registers to Set/Get MAC address.
Parameters:
bar is the BAR register the user driver wants to use.
Returns:
DMABaseAddress
References privData::baseVAddr, dmaData, and INITIALIZED.
void* DmaRegister (int engine, int bar, UserPtrs * uptr, int pktsize)
This function must be called by the user driver to register itself with the base DMA driver. After doing required checks to verify the choice of engine and BAR register, it initializes the engine and the BD ring associated with the engine, and enables interrupts if required.
Only one user is supported per engine at any given time. Incase the engine has already been registered with another user driver, an error will be returned.
Parameters:
engine is the DMA engine the user driver wants to use.
bar is the BAR register the user driver wants to use.
uptr is a pointer to the function callbacks in the user driver.
pktsize is the size of packets that the user driver will normally use.
Returns:
NULL incase of any error in completing the registration.
Handle with which the user driver is registered.
Note:
This function should not be called in an interrupt context
References privData::baseVAddr, Dma_Engine::BdRing, descriptor_init(), privData::Dma, Dma_BdRingStart(), Dma_mEngIntEnable, dmaData, privData::engineMask, Dma_Engine::EngineState, INITIALIZED, Dma_Engine::pdev, Dma_Engine::pktSize, UserPtrs::privData, Dma_Engine::user, USER_ASSIGNED, privData::userCount, UserPtrs::UserInit, and UserPtrs::versionReg.
int DmaUnregister (void * handle)
This function must be called by the user driver to unregister itself from the base DMA driver. After doing required checks to verify the handle and engine state, the DMA engine is reset, interrupts are disabled if required, and the BD ring is freed, while returning all the packet buffers to the user driver.
Parameters:
handle is the handle which was assigned during the registration process.
Returns:
XST_FAILURE incase of any error
0 incase of success
Note:
This function should not be called in an interrupt context
References descriptor_free(), Dma_Reset(), dmaData, Dma_Engine::EngineState, INITIALIZED, Dma_Engine::pdev, UNREGISTERING, USER_ASSIGNED, and privData::userCount.