Kintex-7: xdma/xdma.h File Reference
xdma.h File Reference
#include <linux/timer.h>
#include "xbasic_types.h"
#include "xdma_bdring.h"
#include "xdma_user.h"
#include <xpmon_be.h>
Classes
struct Dma_Engine
struct privData
Defines
#define XDMA_H
#define MAX_BARS 6
#define MAX_DMA_ENGINES 64
#define DMA_ALL_BDS 0xFFFFFFFF
Functions
Initialization and control functions in xdma.c
int descriptor_init (struct pci_dev *pdev, Dma_Engine *eptr)
void descriptor_free (struct pci_dev *pdev, Dma_Engine *eptr)
void Dma_Initialize (Dma_Engine *InstancePtr, u32 BaseAddress, u32 Type)
void Dma_Reset (Dma_Engine *InstancePtr)
Variables
u32 DriverState
spinlock_t DmaLock
spinlock_t DmaTXLock
spinlock_t DmaRXLock
Private per-device data
The PCI device entry points to this as driver-private data. In some cases, pointer back to PCI device entry is also required.
struct privData * dmaData
Detailed Description
The Xilinx Scatter Gather DMA driver for the Northwest Logic DMA Engine. Each DMA engine may either be for TX (System-to-Card or S2C) or RX (Card-to- System or C2S) operation. Each driver instance supports one S2C and one C2S DMA engines, allowing full-duplex operation per instance.
Please note that the Xilinx DMA driver uses only the Packet DMA engine of the Northwest Logic DMA Engine, and not the Block DMA engine type. As such, the description below pertains to the Packet DMA flow.
This component is designed to be used as a basic building block for designing a device driver. It provides register accesses such that all DMA processing can be maintained easier, but the device driver designer must still understand all the details of the DMA channel.
For a full description of DMA features, please see the hardware specification. This driver supports the following features:
Scatter-Gather DMA (SGDMA)
Interrupts
Interrupts are coalesced by the driver to improve performance
32-bit addressing for Buffer Descriptors (BDs) and data buffers
APIs to manage BD movement to and from the SGDMA engine
Virtual memory support
PCI Express support
Performance measurement statistics
APIs to enable DMA driver to be used by other application drivers
Packet DMA Transactions
To describe a DMA transaction in its simplest form, you need source address, destination address, and the number of bytes to transfer. When using a packet DMA receive channel, the source address is within some piece of IP hardware and doesn't require the software to explicitly set it. And the destination address points to a system buffer into which received data must be copied.
Likewise, with a packet DMA transmit channel, the destination address is within the hardware and need not be specified by the software. And the source address points to a system buffer that must be transmitted.
Therefore, some of the packet DMA transaction attributes include:
An application buffer address
The number bytes to transfer
Whether this transaction represents the start of a packet, or end of a packet, or neither (middle of a packet)
The object used to describe a transaction is referred to as a Buffer Descriptor (BD). See xdma_bd.h for a detailed description of and the APIs for manipulation of these objects.
Scatter-Gather DMA (SGDMA)
SGDMA allows the application to define a list of transactions in memory which the hardware will process without further application intervention. During this time, the application is free to continue adding more work to keep the hardware busy.
Notification of completed transactions can be done either by polling the hardware, or using interrupts that signal a transaction has completed, or by examining BDs for a completion status.
SGDMA processes whole packets. A packet is defined as a series of data bytes that represent a message. SGDMA allows a packet of data to be broken up into one or more transactions. For example, take an Ethernet IP packet which consists of a 14-byte header followed by a data payload of one or more bytes. With SGDMA, the application may point a BD to the header and another BD to the payload, then transfer them as a single message. This strategy can make a TCP/IP stack more efficient by allowing it to keep packet headers and data in different memory regions instead of assembling packets into contiguous blocks of memory.
SGDMA Ring Management
The hardware expects BDs to be setup as a singly linked list. As a BD is completed, the DMA engine will dereference BD.Next and load the next BD to process. These BDs may be arranged in a large chain or in a large ring. This driver uses a fixed buffer ring where each BD is linked to the next BD in adjacent memory. The last BD in the ring is linked to the first.
Within the ring, the driver maintains four groups of BDs. Each group consists of 0 or more adjacent BDs:
Free: Those BDs that can be allocated for DMA with Dma_BdRingAlloc().
Pre-process: Those BDs that have been allocated with Dma_BdRingAlloc(). These BDs can now be modified in preparation for future DMA transactions.
Hardware: Those BDs that have been enqueued to hardware with Dma_BdRingToHw(). These BDs are under hardware control and may be in a state of awaiting hardware processing, in process, or processed by hardware. It is considered an error for the driver to change BDs while they are in this group. Doing so can cause data corruption and lead to system instability.
Post-process: Those BDs that have been processed by hardware and have been recovered by the driver with Dma_BdRingFromHw(). These BDs are now under driver control. The driver may access these BDs to determine the result of DMA transactions. When the driver is finished, Dma_BdRingFree() should be called to place them back into the Free group.
Normally BDs are moved in the following way:
         Dma_BdRingAlloc()                      Dma_BdRingToHw()
   Free ------------------------> Pre-process ----------------------> Hardware
                                                                      |
    /|\                                                               |
     |   Dma_BdRingFree()                       Dma_BdRingFromHw()    |
     +--------------------------- Post-process <----------------------+
There are a few exceptions to the flow above. One is that after BDs are moved from the Free group to the Pre-process group, the driver decides for whatever reason that these BDs are not ready and could not be given to hardware. In this case, these BDs could be moved back to Free group using Dma_BdRingUnAlloc() function to help keep the BD ring in great shape and recover the error. See comments of the function for details.
           Dma_BdRingUnAlloc()
   Free <----------------------- Pre-process
The second exception to the flow above is when a registered application-specific driver unregisters from the DMA driver, then the buffers queued for DMA must be retrieved from the BD ring and returned to the driver for freeing. This is the only time that this flow is used.
         Dma_BdRingAlloc()                      Dma_BdRingToHw()
   Free ------------------------> Pre-process ----------------------> Hardware
                                                                        |
    /|\                                                                 |
     |   Dma_BdRingFree()                       Dma_BdRingForceFromHw() |
     +--------------------------- Post-process <------------------------+
The API provides macros that allow BD list traversal. These macros should be used with care as they do not understand where one group ends and another begins.
The driver does not cache or keep copies of any BD. When it modifies BDs returned by Dma_BdRingAlloc() or Dma_BdRingFromHw(), it is modifying the same BD that hardware accesses.
Certain pairs of list modification functions have usage restrictions. See the function headers for Dma_BdRingAlloc() and Dma_BdRingFromHw() for more information.
SGDMA Descriptor Ring Creation
During initialization, the function Dma_BdRingCreate() is used to set up a memory block to contain all BDs for the DMA channel. This function takes as an argument the number of BDs to place in the list.
The caller allocates a memory block large enough to contain the desired number of BDs plus an extra one to take care of any shifting in order to meet the 32-byte alignment needs of the Northwest Logic DMA hardware. This has been covered in more detail below.
Once the list has been created, it can be used right away to perform DMA transactions.
Interrupts
The driver has a compile-time flag to enable either interrupts or polled mode of operation. In some configurations, the polled mode is seen to have better performance than the interrupt mode driver.
When interrupts are enabled, the interrupt handler !!!MUST!!! clear pending interrupts before handling the BDs processed by the DMA engine. Otherwise the following corner case could raise some issue:
A packet is transmitted(/received) and asserts a TX(/RX) interrupt, and if this interrupt handler deals with the BDs finished by the DMA before it clears the interrupt, another packet could get transmitted(/received) and assert the interrupt between when the BDs are taken care and when the interrupt clearing operation begins, and the interrupt clearing operation will clear the interrupt raised by the second packet and will never process it according BDs until a new interrupt occurs.
Changing the sequence to "Clear interrupts before handling BDs" solves this issue:
If the interrupt raised by the second packet is before the interrupt clearing operation, the descriptors associated with the second packet must have been finished by hardware and ready for the handler to deal with, and those descriptors will processed with those BDs of the first packet during the handling of the interrupt asserted by the first packet.
if the interrupt of the second packet is asserted after the interrupt clearing operation but its BDs are finished before the handler starts to deal with BDs, the packet's buffer descriptors will be handled with those of the first packet during the handling of the interrupt asserted by the first packet.
Otherwise, the BDs of the second packet is not ready when the interrupt handler starts to deal with the BDs of the first packet. Those BDs will be handled next time the interrupt handled gets invoked as the interrupt of the second packet is not cleared in current pass and thereby will cause the handler to get invoked again
Please note if the second case above occurs, the handler will find NO buffer descriptor is finished by the hardware (i.e., Dma_BdRingFromHw() returns 0) during the handling of the interrupt asserted by the second packet. This is valid and the driver should NOT consider this is a hardware error and have no need to reset the hardware.
Interrupt Coalescing
On a high-speed link, significant processor overhead may be used in servicing interrupts. Interrupt coalescing can be achieved by the driver enabling BD completion interrupts, not on every BD, but on a set of BDs, thus reducing the frequency of interrupts. The macro INT_COAL_CNT in xdma_hw.h can be used for this purpose.
In addition, the driver processes outstanding BDs to be processed after an idle timeout with no transactions elapses.
Software Initialization
The driver does the following steps in order to prepare the DMA engine to be ready to process DMA transactions:
DMA Initialization using Dma_Initialize() function. This step initializes a driver instance for the given DMA engine and resets the engine. One driver instance exists for a pair of (S2C and C2S) engines.
BD Ring creation. A BD ring is needed per engine and can be built by calling Dma_BdRingCreate(). A parameter passed to this function is the number of BDs fit in a given memory range, and Dma_mBdRingCntCalc() helps calculate the value.
(RX channel only) Prepare BDs with attached data buffers and give them to the RX channel. First, allocate BDs using Dma_BdRingAlloc(), then populate data buffer address, data buffer size and the control word fields of each allocated BD with valid values. Last call Dma_BdRingToHw() to give the BDs to the channel.
Enable interrupts if interrupt mode is chosen. The application is responsible for setting up the interrupt system, which includes providing and connecting interrupt handlers and call back functions, before the interrupts are enabled.
Start DMA channels: Call Dma_BdRingStart() to start a channel
How to start DMA transactions
RX channel is ready to start RX transactions once the initialization (see Initialization section above) is finished. The DMA transactions are triggered by the user IP (like Local Link TEMAC).
Starting TX transactions needs some work. The application calls Dma_BdRingAlloc() to allocate a BD list, then populates necessary attributes of each allocated BD including data buffer address, data size, and control word, and last passes those BDs to the TX channel (see Dma_BdRingToHw()). The added BDs will be processed as soon as the TX channel reaches them.
Software Post-Processing on completed DMA transactions
Some software post-processing is needed after DMA transactions are finished.
If interrupts are set up and enabled, DMA channels notify the software the finishing of DMA transactions using interrupts, Otherwise the application could poll the channels (see Dma_BdRingFromHw()).
Once BDs are finished by a channel, the application first needs to fetch them from the channel (see Dma_BdRingFromHw()).
On TX side, the application now could free the data buffers attached to those BDs as the data in the buffers has been transmitted.
On RX side, the application now could use the received data in the buffers attached to those BDs
For both channels, those BDs need to be freed back to the Free group (see Dma_BdRingFree()) so they are allocatable for future transactions.
On RX side, it is the application's responsibility for having BDs ready to receive data at any time. Otherwise the RX channel will refuse to accept any data once it runs out of RX BDs. As we just freed those hardware completed BDs in the previous step, it is good timing to allocate them back (see Dma_BdRingAlloc()), prepare them, and feed them to the RX channel again (see Dma_BdRingToHw())
Address Translation
When the BD list is setup with Dma_BdRingCreate(), a physical and virtual address is supplied for the segment of memory containing the descriptors. The driver will handle any translations internally. Subsequent access of descriptors by the application is done in terms of their virtual address.
Any application data buffer address attached to a BD must be physical address. The application is responsible for calculating the physical address before assigns it to the buffer address field in the BD.
Memory Barriers
The DMA hardware expects the update to its Next BD pointer register to be the event which initiates DMA processing. Hence, memory barrier wmb() calls have been used to ensure this.
Alignment
For BDs: The Northwest Logic DMA hardware requires BDs to be aligned at 32-byte boundaries. In addition to the this, the driver has its own alignment requirements. It needs to store per-packet information in each BD, for example, the buffer virtual address. In order to do this, the software view of the BD may be larger than the hardware view of the BD. For example, DMA_BD_SW_NUM_WORDS can be set to 16 words (64 bytes), even though DMA_BD_HW_NUM_WORDS is 8 words (32 bytes). Due to this, the driver gets additional space in which to store per-BD private information.
Minimum alignment is defined by the constant DMA_BD_MINIMUM_ALIGNMENT. This is the smallest alignment allowed by both hardware and software for them to properly work. Other than DMA_BD_MINIMUM_ALIGNMENT, multiples of the constant are the only valid alignments for BDs.
If the descriptor ring is to be placed in cached memory, alignment also MUST be at least the processor's cache-line size. If this requirement is not met then system instability will result. This is also true if the length of a BD is longer than one cache-line, in which case multiple cache-lines are needed to accommodate each BD.
Aside from the initial creation of the descriptor ring (see Dma_BdRingCreate()), there are no other run-time checks for proper alignment.
For application data buffers: Application data buffer alignment is taken care of by the application-specific drivers.
Reset After Stopping
This driver is designed to allow for stop-reset-start cycles of the DMA hardware while keeping the BD list intact. When restarted after a reset, this driver will point the DMA engine to where it left off after stopping it.
It is possible to load an application-specific driver, run it for some time, and then unload it. Without unloading the DMA driver as well, it should be possible to load another instance of the application-specific driver and it should work fine.
MODIFICATION HISTORY:
Ver Date Changes ----- -------- ------------------------------------------------------- 1.0 05/15/12 First version
Define Documentation
#define DMA_ALL_BDS 0xFFFFFFFF
Indicates all valid BDs
#define MAX_BARS 6
Maximum number of BARs
#define MAX_DMA_ENGINES 64
Maximum number of DMA engines
Function Documentation
void descriptor_free (struct pci_dev * pdev, Dma_Engine * eptr)
In order to free allocated space (and avoid memory leaks), this function is called when the user driver unregisters itself from the DMA base driver. It does the following -
Forcibly retrieves the buffers which have been queued up for DMA with the DMA engine hardware
Unmaps these buffers from the PCI/PCIe space
Returns these buffers to the user driver, which will free them
Frees the BD ring
De-allocates the space used for the BD ring, and unmaps it from the PCI/PCIe space
Parameters:
pdev is the PCI/PCIe device instance
eptr is a pointer to the DMA engine instance to be worked on.
Returns:
None.
References Dma_Engine::BdRing, PktBuf::bufInfo, Dma_Engine::delta, Dma_Engine::descSpacePA, Dma_Engine::descSpaceSize, Dma_Engine::descSpaceVA, DMA_BD_CNT, Dma_BdRingForceFromHw(), Dma_BdRingFree(), Dma_mBdGetBufAddr, Dma_mBdGetCtrlLength, Dma_mBdGetId, Dma_mBdRingNext, Dma_mBdSetId, PktBuf::flags, Dma_BdRing::IsRxChannel, PktBuf::pageAddr, PKT_UNUSED, PktBuf::pktBuf, UserPtrs::privData, PktBuf::size, Dma_Engine::user, PktBuf::userInfo, and UserPtrs::UserPutPkt.
Referenced by DmaUnregister().
int descriptor_init (struct pci_dev * pdev, Dma_Engine * eptr)
This function initializes the DMA BD ring as follows -
Calculates the space required by the DMA BD ring
Allocates the space, and aligns it as per DMA engine requirement
Creates the BD ring structure in the allocated space
If it is a RX DMA engine, allocates buffers from the user driver, and associates each BD in the RX BD ring with a buffer
Parameters:
pdev is the PCI/PCIe device instance
eptr is a pointer to the DMA engine instance to be worked on.
Returns:
0 if successful
negative value if unsuccessful
References Dma_Engine::BdRing, Dma_Engine::delta, Dma_Engine::descSpacePA, Dma_Engine::descSpaceSize, Dma_Engine::descSpaceVA, DMA_BD_CNT, DMA_BD_MINIMUM_ALIGNMENT, DMA_BD_SW_NUM_WORDS, Dma_BdRingAlign(), Dma_BdRingCreate(), DMA_ENG_C2S, DMA_ENG_DIRECTION_MASK, Dma_Engine::Type, and Dma_Engine::user.
Referenced by DmaRegister().
void Dma_Initialize (Dma_Engine * InstancePtr, u32 BaseAddress, u32 Type)
This function initializes a DMA engine. This function must be called prior to using the DMA engine. Initialization of an engine includes setting up the register base address, setting up the instance data, and ensuring the hardware is in a quiescent state.
Parameters:
InstancePtr is a pointer to the DMA engine instance to be worked on.
BaseAddress is where the registers for this engine can be found.
Returns:
None.
References Dma_Engine::BdRing, DMA_ENG_C2S, Dma_Reset(), Dma_Engine::EngineState, INITIALIZED, Dma_BdRing::IsRxChannel, Dma_Engine::RegBase, Dma_BdRing::RunState, and Dma_Engine::Type.
void Dma_Reset (Dma_Engine * InstancePtr)
Reset the DMA engine.
Should not be invoked during initialization stage because hardware has just come out of a system reset. Should be invoked during shutdown stage.
New BD fetches will stop immediately. Reset will be completed once the user logic completes its reset. DMA disable will be completed when the BDs already being processed are completed.
Parameters:
InstancePtr is a pointer to the DMA engine instance to be worked on.
Returns:
None.
Note:
If the hardware is not working properly, and the self-clearing reset bits do not clear, this function will be terminated after a timeout.
References DMA_ENG_ALLINT_MASK, DMA_ENG_DISABLE, DMA_ENG_INT_ACTIVE_MASK, DMA_ENG_RESET, DMA_ENG_STATE_MASK, DMA_ENG_USER_RESET, Dma_mEngIntAck, Dma_mEngIntDisable, Dma_mGetCrSr, Dma_mGetRing, Dma_mSetCrSr, and Dma_BdRing::RunState.
Referenced by Dma_Initialize(), and DmaUnregister().
Variable Documentation
struct privData* dmaData
DMA driver state-related variables
Referenced by DmaBaseAddress(), DmaRegister(), and DmaUnregister().