Kintex-7: xdma/xdma_base.c File Reference
xdma_base.c File Reference
#include <linux/pci.h>
#include <linux/interrupt.h>
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/spinlock.h>
#include <linux/fs.h>
#include <linux/types.h>
#include <linux/kdev_t.h>
#include <linux/cdev.h>
#include <asm/uaccess.h>
#include <linux/version.h>
#include <linux/ethtool.h>
#include <linux/mm.h>
#include <linux/pagemap.h>
#include <asm/scatterlist.h>
#include <linux/delay.h>
#include <xpmon_be.h>
#include "xdebug.h"
#include "xbasic_types.h"
#include "xstatus.h"
#include "xdma.h"
#include "xdma_hw.h"
#include "xdma_bdring.h"
#include "xdma_user.h"
Classes
struct PktPool
Defines
#define DMA_ENGINE_PER_SIZE 0x100
#define DMA_OFFSET 0
#define DMA_SIZE (MAX_DMA_ENGINES * DMA_ENGINE_PER_SIZE)
#define DMA_BD_CNT 1999
#define MAX_POOL 10
#define MAX_STATS 100
#define TX_UTIL_BC 0x900c
#define RX_UTIL_BC 0x9010
#define UPSTR_MEMWR_BC 0x9014
#define DOWNSTR_COMPBYTE_COUNTR 0x9018
#define MInitFCCplD 0x901c
#define MInitFCCplH 0x9020
#define MInitFCNPD 0x9024
#define MInitFCNPH 0x9028
#define MInitFCPD 0x902c
#define MInitFCPH 0x9030
#define PCIE_DESIGN_VERSION 0x9000
#define PM_OPS NULL
Functions
DEFINE_SPINLOCK (DmaLock)
struct PktPool * DQPool (void)
void EQPool (struct PktPool *pp)
int descriptor_init (struct pci_dev *pdev, Dma_Engine *eptr)
void descriptor_free (struct pci_dev *pdev, Dma_Engine *eptr)
module_init (xdma_init)
module_exit (xdma_cleanup)
EXPORT_SYMBOL (DmaRegister)
EXPORT_SYMBOL (DmaUnregister)
EXPORT_SYMBOL (DmaBaseAddress)
EXPORT_SYMBOL (DmaMac_WriteReg)
EXPORT_SYMBOL (DmaMac_ReadReg)
EXPORT_SYMBOL (DmaSendPages)
EXPORT_SYMBOL (DmaSendPkt)
EXPORT_SYMBOL (DmaSendPages_Tx)
EXPORT_SYMBOL (Dma_get_ringparam)
Variables
PktBuf pktArray [MAX_POOL][DMA_BD_CNT]
struct PktPool pktPool [MAX_POOL]
struct PktPool * pktPoolHead = NULL
struct PktPool * pktPoolTail = NULL
struct timer_list stats_timer
struct timer_list poll_timer
struct cdev * xdmaCdev = NULL
struct privData * dmaData = NULL
u32 DriverState = UNINITIALIZED
int UserOpen = 0
DMAStatistics DStats [MAX_DMA_ENGINES][MAX_STATS]
SWStatistics SStats [MAX_DMA_ENGINES][MAX_STATS]
TRNStatistics TStats [MAX_STATS]
int dstatsRead [MAX_DMA_ENGINES]
int dstatsWrite [MAX_DMA_ENGINES]
int dstatsNum [MAX_DMA_ENGINES]
int sstatsRead [MAX_DMA_ENGINES]
int sstatsWrite [MAX_DMA_ENGINES]
int sstatsNum [MAX_DMA_ENGINES]
int tstatsRead
int tstatsWrite
int tstatsNum
u32 SWrate [MAX_DMA_ENGINES]
Macros for PCI probing
#define PCI_VENDOR_ID_DMA 0x10EE
#define PCI_DEVICE_ID_DMA 0x7082
#define DRIVER_NAME "xdma_driver"
#define DRIVER_DESCRIPTION "Xilinx DMA Linux driver"
#define DRIVER_VERSION "1.0"
MODULE_AUTHOR ("Xilinx, Inc.")
MODULE_DESCRIPTION (DRIVER_DESCRIPTION)
MODULE_VERSION (DRIVER_VERSION)
MODULE_LICENSE ("GPL")
MODULE_DEVICE_TABLE (pci, ids)
Detailed Description
This is the Linux base driver for the DMA engine core. It provides multi-channel DMA capability with the help of the Northwest Logic DMA engine.
Author: Xilinx, Inc.
2007-2010 (c) Xilinx, Inc. This file is licensed uner the terms of the GNU General Public License version 2.1. This program is licensed "as is" without any warranty of any kind, whether express or implied.
MODIFICATION HISTORY:
Ver Date Changes ----- -------- ------------------------------------------------------- 1.0 5/15/12 First release
Define Documentation
#define DMA_BD_CNT 1999
Default S2C and C2S descriptor ring size. BD Space needed is (DMA_BD_CNT*sizeof(Dma_Bd)).
Referenced by descriptor_free(), and descriptor_init().
#define DMA_ENGINE_PER_SIZE 0x100
Engine bitmask is 64-bit because there are 64 engines Separation between engine regs
#define DMA_OFFSET 0
Starting register offset Size of DMA engine reg space
#define DRIVER_NAME "xdma_driver"
Driver information
#define PCI_DEVICE_ID_DMA 0x7082
Xilinx's Device ID
#define PCI_VENDOR_ID_DMA 0x10EE
Vendor ID - Xilinx
Function Documentation
void descriptor_free (struct pci_dev * pdev, Dma_Engine * eptr)
In order to free allocated space (and avoid memory leaks), this function is called when the user driver unregisters itself from the DMA base driver. It does the following -
Forcibly retrieves the buffers which have been queued up for DMA with the DMA engine hardware
Unmaps these buffers from the PCI/PCIe space
Returns these buffers to the user driver, which will free them
Frees the BD ring
De-allocates the space used for the BD ring, and unmaps it from the PCI/PCIe space
Parameters:
pdev is the PCI/PCIe device instance
eptr is a pointer to the DMA engine instance to be worked on.
Returns:
None.
References Dma_Engine::BdRing, PktBuf::bufInfo, Dma_Engine::delta, Dma_Engine::descSpacePA, Dma_Engine::descSpaceSize, Dma_Engine::descSpaceVA, DMA_BD_CNT, Dma_BdRingForceFromHw(), Dma_BdRingFree(), Dma_mBdGetBufAddr, Dma_mBdGetCtrlLength, Dma_mBdGetId, Dma_mBdRingNext, Dma_mBdSetId, PktBuf::flags, Dma_BdRing::IsRxChannel, PktBuf::pageAddr, PKT_UNUSED, PktBuf::pktBuf, UserPtrs::privData, PktBuf::size, Dma_Engine::user, PktBuf::userInfo, and UserPtrs::UserPutPkt.
Referenced by DmaUnregister().
int descriptor_init (struct pci_dev * pdev, Dma_Engine * eptr)
This function initializes the DMA BD ring as follows -
Calculates the space required by the DMA BD ring
Allocates the space, and aligns it as per DMA engine requirement
Creates the BD ring structure in the allocated space
If it is a RX DMA engine, allocates buffers from the user driver, and associates each BD in the RX BD ring with a buffer
Parameters:
pdev is the PCI/PCIe device instance
eptr is a pointer to the DMA engine instance to be worked on.
Returns:
0 if successful
negative value if unsuccessful
References Dma_Engine::BdRing, Dma_Engine::delta, Dma_Engine::descSpacePA, Dma_Engine::descSpaceSize, Dma_Engine::descSpaceVA, DMA_BD_CNT, DMA_BD_MINIMUM_ALIGNMENT, DMA_BD_SW_NUM_WORDS, Dma_BdRingAlign(), Dma_BdRingCreate(), DMA_ENG_C2S, DMA_ENG_DIRECTION_MASK, Dma_Engine::Type, and Dma_Engine::user.
Referenced by DmaRegister().
MODULE_AUTHOR (" Xilinx, Inc.")
Driver Module information
MODULE_DEVICE_TABLE (pci , ids)
Macro to export pci_device_id to user space to allow hot plug and module loading system to know what module works with which hardware device
Variable Documentation
struct privData* dmaData = NULL
DMA driver state-related variables
Referenced by DmaBaseAddress(), DmaRegister(), and DmaUnregister().