Kintex-7: xdma/xdma_bdring.c File Reference
xdma_bdring.c File Reference
#include <linux/kernel.h>
#include <linux/string.h>
#include <linux/ethtool.h>
#include "xbasic_types.h"
#include "xdebug.h"
#include "xstatus.h"
#include "xio.h"
#include "xdma_bdring.h"
#include "xdma_hw.h"
Functions
int Dma_BdRingCreate (Dma_BdRing *RingPtr, u32 PhysAddr, u32 VirtAddr, u32 Alignment, unsigned BdCount)
int Dma_BdRingStart (Dma_BdRing *RingPtr)
int Dma_BdRingAlloc (Dma_BdRing *RingPtr, unsigned NumBd, Dma_Bd **BdSetPtr)
int Dma_BdRingUnAlloc (Dma_BdRing *RingPtr, unsigned NumBd, Dma_Bd *BdSetPtr)
int Dma_BdRingToHw (Dma_BdRing *RingPtr, unsigned NumBd, Dma_Bd *BdSetPtr)
unsigned Dma_BdRingFromHw (Dma_BdRing *RingPtr, unsigned BdLimit, Dma_Bd **BdSetPtr)
unsigned Dma_BdRingForceFromHw (Dma_BdRing *RingPtr, unsigned BdLimit, Dma_Bd **BdSetPtr)
int Dma_BdRingFree (Dma_BdRing *RingPtr, unsigned NumBd, Dma_Bd *BdSetPtr)
int Dma_BdRingCheck (Dma_BdRing *RingPtr)
u32 Dma_BdRingAlign (u32 AllocPtr, u32 Size, u32 Align, u32 *Delta)
Detailed Description
This file implements buffer descriptor ring related functions. For more information on this driver, see xdma.h.
MODIFICATION HISTORY:
Ver Date Changes ----- -------- ------------------------------------------------------- 1.0 5/15/12 First release
Function Documentation
u32 Dma_BdRingAlign (u32 AllocPtr, u32 Size, u32 Align, u32 * Delta)
Align the BD space.
The DMA engine requires aligned BDs. This function aligns the space as required by the caller.
Parameters:
AllocPtr is the virtual address of the allocated BD space.
Size is the size of the allocated BD space.
Align is the number of bytes of alignment required.
Delta is the shift required in virtual and physical addresses in order to achieve the alignment. This should be applied by the caller.
Returns:
Number of BDs that will fit in the re-aligned BD space.
Note:
References DMA_BD_SW_NUM_WORDS.
Referenced by descriptor_init().
int Dma_BdRingAlloc (Dma_BdRing * RingPtr, unsigned NumBd, Dma_Bd ** BdSetPtr)
Reserve locations in the BD ring. The set of returned BDs may be modified in preparation for future DMA transactions. Once the BDs are ready to be submitted to hardware, the application must call Dma_BdRingToHw() in the same order which they were allocated here. Example:
        NumBd = 2;
        Status = Dma_RingBdAlloc(MyRingPtr, NumBd, &MyBdSet);
        if (Status != XST_SUCCESS)
        {
            // Not enough BDs available for the request
        }
        CurBd = MyBdSet;
        for (i=0; i<NumBd; i++)
        {
            // Prepare CurBd.....
            // Onto next BD
            CurBd = Dma_mBdRingNext(MyRingPtr, CurBd);
        }
        // Give list to hardware
        Status = Dma_BdRingToHw(MyRingPtr, NumBd, MyBdSet);
A more advanced use of this function may allocate multiple sets of BDs. They must be allocated and given to hardware in the correct sequence:
        // Legal
        Dma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1);
        Dma_BdRingToHw(MyRingPtr, NumBd1, MySet1);
        // Legal
        Dma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1);
        Dma_BdRingAlloc(MyRingPtr, NumBd2, &MySet2);
        Dma_BdRingToHw(MyRingPtr, NumBd1, MySet1);
        Dma_BdRingToHw(MyRingPtr, NumBd2, MySet2);
        // Not legal
        Dma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1);
        Dma_BdRingAlloc(MyRingPtr, NumBd2, &MySet2);
        Dma_BdRingToHw(MyRingPtr, NumBd2, MySet2);
        Dma_BdRingToHw(MyRingPtr, NumBd1, MySet1);
Use the APIs defined in xdma_bd.h to modify individual BDs. Traversal of the BD set can be done using Dma_mBdRingNext() and Dma_mBdRingPrev().
Parameters:
RingPtr is a pointer to the descriptor ring instance to be worked on.
NumBd is the number of BDs to allocate
BdSetPtr is an output parameter, it points to the first BD available for modification.
Returns:
XST_SUCCESS if the requested number of BDs was returned in the BdSetPtr parameter.
XST_FAILURE if there were not enough free BDs to satisfy the request.
Note:
This function should not be preempted by another Dma_BdRing function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
Do not modify more BDs than the number requested with the NumBd parameter. Doing so will lead to data corruption and system instability.
References Dma_BdRing::FreeCnt, Dma_BdRing::FreeHead, and Dma_BdRing::PreCnt.
int Dma_BdRingCheck (Dma_BdRing * RingPtr)
Check the internal data structures of the BD ring for the provided channel. The following checks are made:
Is the BD ring linked correctly in physical address space.
Do the internal pointers point to BDs in the ring.
Do the internal counters add up.
The channel should be stopped prior to calling this function.
Parameters:
RingPtr is a pointer to the descriptor ring to be worked on.
Returns:
XST_SUCCESS if no errors were found.
XST_DMA_SG_NO_LIST if the ring has not been created.
XST_IS_STARTED if the channel is not stopped.
XST_DMA_SG_LIST_ERROR if a problem is found with the internal data structures. If this value is returned, the channel should be reset to avoid data corruption or system instability.
Note:
This function should not be preempted by another Dma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References Dma_BdRing::AllCnt, DMA_BD_NDESC_OFFSET, Dma_mBdRead, Dma_BdRing::FirstBdAddr, Dma_BdRing::FirstBdPhysAddr, Dma_BdRing::FreeCnt, Dma_BdRing::FreeHead, Dma_BdRing::HwCnt, Dma_BdRing::HwHead, Dma_BdRing::HwTail, Dma_BdRing::LastBdAddr, Dma_BdRing::PostCnt, Dma_BdRing::PostHead, Dma_BdRing::PreCnt, Dma_BdRing::PreHead, Dma_BdRing::RunState, and Dma_BdRing::Separation.
int Dma_BdRingCreate (Dma_BdRing * RingPtr, u32 PhysAddr, u32 VirtAddr, u32 Alignment, unsigned BdCount)
Using a memory segment allocated by the caller, create and setup the BD list for the given SGDMA ring.
Parameters:
RingPtr is the ring to be worked on.
PhysAddr is the physical base address of allocated memory region.
VirtAddr is the virtual base address of the allocated memory region.
Alignment governs the byte alignment of individual BDs. This function will enforce a minimum alignment of DMA_BD_MINIMUM_ALIGNMENT bytes with no maximum as long as it is specified as a power of 2.
BdCount is the number of BDs to set up in the application memory region. It is assumed the region is large enough to contain the BDs. Refer to the "SGDMA Descriptor Ring Creation" section in xdma.h for more information. The minimum valid value for this parameter is 1.
Returns:
XST_SUCCESS if initialization was successful
XST_INVALID_PARAM under any of the following conditions: 1) PhysAddr and/or VirtAddr are not aligned to the given Alignment parameter; 2) Alignment parameter does not meet minimum requirements or is not a power of 2 value; 3) BdCount is 0.
XST_DMA_SG_LIST_ERROR if the memory segment containing the list spans over address 0x00000000 in virtual address space.
References Dma_BdRing::AllCnt, Dma_BdRing::BdaRestart, Dma_BdRing::BDerrs, Dma_BdRing::BDSerrs, DMA_BD_MINIMUM_ALIGNMENT, DMA_BD_NDESC_OFFSET, Dma_mBdWrite, Dma_BdRing::FirstBdAddr, Dma_BdRing::FirstBdPhysAddr, Dma_BdRing::FreeCnt, Dma_BdRing::FreeHead, Dma_BdRing::HwCnt, Dma_BdRing::HwHead, Dma_BdRing::HwTail, Dma_BdRing::IsRxChannel, Dma_BdRing::LastBdAddr, Dma_BdRing::Length, Dma_BdRing::PostCnt, Dma_BdRing::PostHead, Dma_BdRing::PreCnt, Dma_BdRing::PreHead, Dma_BdRing::RunState, and Dma_BdRing::Separation.
Referenced by descriptor_init().
unsigned Dma_BdRingForceFromHw (Dma_BdRing * RingPtr, unsigned BdLimit, Dma_Bd ** BdSetPtr)
Returns a set of BDs that had been enqueued to hardware, whether the hardware has processed them yet or not. This should be called only when the driver is freeing up buffers and about to free the ring. The returned BDs may be examined by the caller in order to recover the buffers. Once the BDs have been examined, the caller must call Dma_BdRingFree() in the same order which they were retrieved here.
Parameters:
RingPtr is a pointer to the descriptor ring instance to be worked on.
BdLimit is the maximum number of BDs to return in the set. Use DMA_ALL_BDS to return all BDs that have been processed.
BdSetPtr is an output parameter, it points to the first BD available for examination.
Returns:
The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned.
Note:
Treat BDs returned by this function as read-only.
This function should not be preempted by another Dma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References DMA_BD_ERROR_MASK, Dma_mBdGetStatus, Dma_mBdRingNext, Dma_BdRing::HwCnt, Dma_BdRing::HwHead, Dma_BdRing::HwTail, and Dma_BdRing::PostCnt.
Referenced by descriptor_free().
int Dma_BdRingFree (Dma_BdRing * RingPtr, unsigned NumBd, Dma_Bd * BdSetPtr)
Frees a set of BDs that had been previously retrieved with Dma_BdRingFromHw(). This function also clear all control/status bits (like SOP/EOP) of each BD in the set.
Parameters:
RingPtr is a pointer to the descriptor ring instance to be worked on.
NumBd is the number of BDs to free.
BdSetPtr is the head of a list of BDs returned by Dma_BdRingFromHw().
Returns:
XST_SUCCESS if the set of BDs was freed.
XST_DMA_SG_LIST_ERROR if this function was called out of sequence with Dma_BdRingFromHw().
Note:
This function should not be preempted by another Dma function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References DMA_BD_BUFL_CTRL_OFFSET, DMA_BD_BUFL_STATUS_OFFSET, Dma_mBdRingNext, Dma_mBdWrite, Dma_BdRing::FreeCnt, Dma_BdRing::PostCnt, and Dma_BdRing::PostHead.
Referenced by descriptor_free().
unsigned Dma_BdRingFromHw (Dma_BdRing * RingPtr, unsigned BdLimit, Dma_Bd ** BdSetPtr)
Returns a set of BDs that have been processed by hardware. The returned BDs may be examined by the caller to determine the outcome of the DMA transactions. Once the BDs have been examined, the caller must call Dma_BdRingFree() in the same order which they were retrieved here.
Example:
        NumBd = Dma_BdRingFromHw(MyRingPtr, DMA_ALL_BDS, &MyBdSet);
        if (NumBd == 0)
        {
           // hardware has nothing ready for us yet.
        }
        CurBd = MyBdSet;
        for (i=0; i<NumBd; i++)
        {
           // Examine CurBd for post processing.....
           // Onto next BD
           CurBd = Dma_mBdRingNext(MyRingPtr, CurBd);
        }
        Dma_BdRingFree(MyRingPtr, NumBd, MyBdSet); // Return the list
A more advanced use of this function may allocate multiple sets of BDs. They must be retrieved from hardware and freed in the correct sequence:
        // Legal
        Dma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1);
        Dma_BdRingFree(MyRingPtr, NumBd1, MySet1);
        // Legal
        Dma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1);
        Dma_BdRingFromHw(MyRingPtr, NumBd2, &MySet2);
        Dma_BdRingFree(MyRingPtr, NumBd1, MySet1);
        Dma_BdRingFree(MyRingPtr, NumBd2, MySet2);
        // Not legal
        Dma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1);
        Dma_BdRingFromHw(MyRingPtr, NumBd2, &MySet2);
        Dma_BdRingFree(MyRingPtr, NumBd2, MySet2);
        Dma_BdRingFree(MyRingPtr, NumBd1, MySet1);
If hardware has partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results.
Parameters:
RingPtr is a pointer to the descriptor ring instance to be worked on.
BdLimit is the maximum number of BDs to return in the set. Use DMA_ALL_BDS to return all BDs that have been processed.
BdSetPtr is an output parameter, it points to the first BD available for examination.
Returns:
The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned.
Note:
Treat BDs returned by this function as read-only.
This function should not be preempted by another Dma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References Dma_BdRing::BDerrs, Dma_BdRing::BDSerrs, DMA_BD_BUFAL_OFFSET, DMA_BD_COMP_MASK, DMA_BD_EOP_MASK, DMA_BD_ERROR_MASK, DMA_BD_NDESC_OFFSET, DMA_BD_SHORT_MASK, DMA_BD_USER_HIGH_ZERO_MASK, DMA_BD_USER_LOW_ZERO_MASK, Dma_mBdGetCtrl, Dma_mBdGetStatus, Dma_mBdRead, Dma_mBdRingNext, Dma_mReadReg, Dma_BdRing::HwCnt, Dma_BdRing::HwHead, Dma_BdRing::HwTail, Dma_BdRing::IsRxChannel, and Dma_BdRing::PostCnt.
int Dma_BdRingStart (Dma_BdRing * RingPtr)
Allow DMA transactions to commence on the given channels if descriptors are ready to be processed.
Parameters:
EngPtr is a pointer to the engine instance to be worked on.
Returns:
XST_SUCCESS if the channel was started.
XST_DMA_SG_NO_LIST if the channel has no initialized BD ring.
References Dma_BdRing::AllCnt, Dma_BdRing::BdaRestart, Dma_mEnable, Dma_mReadReg, Dma_mVirtToPhys, Dma_mWriteReg, Dma_BdRing::HwCnt, Dma_BdRing::HwTail, Dma_BdRing::IsRxChannel, REG_DMA_ENG_NEXT_BD, REG_SW_NEXT_BD, and Dma_BdRing::RunState.
Referenced by DmaRegister().
int Dma_BdRingToHw (Dma_BdRing * RingPtr, unsigned NumBd, Dma_Bd * BdSetPtr)
Enqueue a set of BDs to hardware that were previously allocated by Dma_BdRingAlloc(). Once this function returns, the argument BD set goes under hardware control. Any changes made to these BDs after this point will corrupt the BD list leading to data corruption and system instability.
The set will be rejected if the last BD of the set does not mark the end of a packet.
Parameters:
RingPtr is a pointer to the descriptor ring instance to be worked on.
NumBd is the number of BDs in the set.
BdSetPtr is the first BD of the set to commit to hardware.
Returns:
XST_SUCCESS if the set of BDs was accepted and enqueued to hardware
XST_FAILURE if the set of BDs was rejected because the first BD did not have its start-of-packet bit set, the last BD did not have its end-of-packet bit set, or any one of the BD set has 0 as length value
XST_DMA_SG_LIST_ERROR if this function was called out of sequence with Dma_BdRingAlloc()
Note:
This function should not be preempted by another Dma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References DMA_BD_BUFL_CTRL_OFFSET, DMA_BD_BUFL_MASK, DMA_BD_EOP_MASK, DMA_BD_SOP_MASK, Dma_mBdRead, Dma_mBdRingNext, Dma_mBdSetStatus, Dma_mVirtToPhys, Dma_mWriteReg, Dma_BdRing::HwCnt, Dma_BdRing::HwTail, Dma_BdRing::IsRxChannel, Dma_BdRing::PreCnt, Dma_BdRing::PreHead, REG_SW_NEXT_BD, and Dma_BdRing::RunState.
int Dma_BdRingUnAlloc (Dma_BdRing * RingPtr, unsigned NumBd, Dma_Bd * BdSetPtr)
Fully or partially undo a Dma_BdRingAlloc() operation. Use this function if all the BDs allocated by Dma_BdRingAlloc() could not be transferred to hardware with Dma_BdRingToHw().
This function helps out in situations when an unrelated error occurs after BDs have been allocated but before they have been given to hardware.
This function is not the same as Dma_BdRingFree(). The Free function returns BDs to the free list after they have been processed by hardware, while UnAlloc returns them before being processed by hardware.
There are two scenarios where this function can be used. Full UnAlloc or Partial UnAlloc. A Full UnAlloc means all the BDs Alloc'd will be returned:
    Status = Dma_BdRingAlloc(MyRingPtr, 10, &BdPtr);    if (Error)
    {
        Status = Dma_BdRingUnAlloc(MyRingPtr, 10, &BdPtr);
    }
A partial UnAlloc means some of the BDs Alloc'd will be returned:
    Status = Dma_BdRingAlloc(MyRingPtr, 10, &BdPtr);
    BdsLeft = 10;
    CurBdPtr = BdPtr;
    while (BdsLeft)
    {
       if (Error)
       {
          Status = Dma_BdRingUnAlloc(MyRingPtr, BdsLeft, CurBdPtr);
       }
       CurBdPtr = Dma_mBdRingNext(MyRingPtr, CurBdPtr);
       BdsLeft--;
    }
A partial UnAlloc must include the last BD in the list that was Alloc'd.
Parameters:
RingPtr is a pointer to the descriptor ring instance to be worked on.
NumBd is the number of BDs to unallocate
BdSetPtr points to the first of the BDs to be returned.
Returns:
XST_SUCCESS if the BDs were unallocated.
XST_FAILURE if NumBd parameter was greater that the number of BDs in the preprocessing state.
Note:
This function should not be preempted by another Dma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References Dma_BdRing::FreeCnt, Dma_BdRing::FreeHead, and Dma_BdRing::PreCnt.