Kintex-7: xdma/xdma.c File Reference
xdma.c File Reference
#include <linux/string.h>
#include <linux/kernel.h>
#include "xbasic_types.h"
#include "xdebug.h"
#include "xstatus.h"
#include "xio.h"
#include "xdma.h"
#include "xdma_hw.h"
Functions
void Dma_Initialize (Dma_Engine *InstancePtr, u32 BaseAddress, u32 Type)
void Dma_Reset (Dma_Engine *InstancePtr)
Detailed Description
This file implements initialization and control related functions. For more information on this driver, see xdma.h.
MODIFICATION HISTORY:
Ver Date Changes ----- ------- ----------------------------------------------------------- 1.0 5/15/12 First release
Function Documentation
void Dma_Initialize (Dma_Engine * InstancePtr, u32 BaseAddress, u32 Type)
This function initializes a DMA engine. This function must be called prior to using the DMA engine. Initialization of an engine includes setting up the register base address, setting up the instance data, and ensuring the hardware is in a quiescent state.
Parameters:
InstancePtr is a pointer to the DMA engine instance to be worked on.
BaseAddress is where the registers for this engine can be found.
Returns:
None.
References Dma_Engine::BdRing, DMA_ENG_C2S, Dma_Reset(), Dma_Engine::EngineState, INITIALIZED, Dma_BdRing::IsRxChannel, Dma_Engine::RegBase, Dma_BdRing::RunState, and Dma_Engine::Type.
void Dma_Reset (Dma_Engine * InstancePtr)
Reset the DMA engine.
Should not be invoked during initialization stage because hardware has just come out of a system reset. Should be invoked during shutdown stage.
New BD fetches will stop immediately. Reset will be completed once the user logic completes its reset. DMA disable will be completed when the BDs already being processed are completed.
Parameters:
InstancePtr is a pointer to the DMA engine instance to be worked on.
Returns:
None.
Note:
If the hardware is not working properly, and the self-clearing reset bits do not clear, this function will be terminated after a timeout.
References DMA_ENG_ALLINT_MASK, DMA_ENG_DISABLE, DMA_ENG_INT_ACTIVE_MASK, DMA_ENG_RESET, DMA_ENG_STATE_MASK, DMA_ENG_USER_RESET, Dma_mEngIntAck, Dma_mEngIntDisable, Dma_mGetCrSr, Dma_mGetRing, Dma_mSetCrSr, and Dma_BdRing::RunState.
Referenced by Dma_Initialize(), and DmaUnregister().