/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xilinx_gui_DriverInfoRaw */

#ifndef _Included_com_xilinx_gui_DriverInfoRaw
#define _Included_com_xilinx_gui_DriverInfoRaw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xilinx_gui_DriverInfoRaw_init
  (JNIEnv *, jclass);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    flush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_flush
  (JNIEnv *, jobject);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    get_PCIstate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_get_1PCIstate
  (JNIEnv *, jobject);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    get_EngineState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_get_1EngineState
  (JNIEnv *, jobject);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    get_DMAStats
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_get_1DMAStats
  (JNIEnv *, jobject);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    get_TRNStats
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_get_1TRNStats
  (JNIEnv *, jobject);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    get_SWStats
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_get_1SWStats
  (JNIEnv *, jobject);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    get_PowerStats
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_get_1PowerStats
  (JNIEnv *, jobject);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    startTest
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_startTest
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    stopTest
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_stopTest
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    setLinkSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_setLinkSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xilinx_gui_DriverInfoRaw
 * Method:    setLinkWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_setLinkWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xilinx_gui_DriverInfoGen
 * Method:    LedStats
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xilinx_gui_DriverInfoRaw_LedStats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
